// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: joex/v1/job.proto

package joexv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ashep/joex/sdk/proto/joex/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// JobServiceName is the fully-qualified name of the JobService service.
	JobServiceName = "joex.v1.JobService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// JobServiceCreateJobProcedure is the fully-qualified name of the JobService's CreateJob RPC.
	JobServiceCreateJobProcedure = "/joex.v1.JobService/CreateJob"
)

// JobServiceClient is a client for the joex.v1.JobService service.
type JobServiceClient interface {
	CreateJob(context.Context, *v1.CreateJobRequest) (*v1.CreateJobResponse, error)
}

// NewJobServiceClient constructs a client for the joex.v1.JobService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewJobServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) JobServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	jobServiceMethods := v1.File_joex_v1_job_proto.Services().ByName("JobService").Methods()
	return &jobServiceClient{
		createJob: connect.NewClient[v1.CreateJobRequest, v1.CreateJobResponse](
			httpClient,
			baseURL+JobServiceCreateJobProcedure,
			connect.WithSchema(jobServiceMethods.ByName("CreateJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// jobServiceClient implements JobServiceClient.
type jobServiceClient struct {
	createJob *connect.Client[v1.CreateJobRequest, v1.CreateJobResponse]
}

// CreateJob calls joex.v1.JobService.CreateJob.
func (c *jobServiceClient) CreateJob(ctx context.Context, req *v1.CreateJobRequest) (*v1.CreateJobResponse, error) {
	response, err := c.createJob.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// JobServiceHandler is an implementation of the joex.v1.JobService service.
type JobServiceHandler interface {
	CreateJob(context.Context, *v1.CreateJobRequest) (*v1.CreateJobResponse, error)
}

// NewJobServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewJobServiceHandler(svc JobServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	jobServiceMethods := v1.File_joex_v1_job_proto.Services().ByName("JobService").Methods()
	jobServiceCreateJobHandler := connect.NewUnaryHandlerSimple(
		JobServiceCreateJobProcedure,
		svc.CreateJob,
		connect.WithSchema(jobServiceMethods.ByName("CreateJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/joex.v1.JobService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case JobServiceCreateJobProcedure:
			jobServiceCreateJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedJobServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedJobServiceHandler struct{}

func (UnimplementedJobServiceHandler) CreateJob(context.Context, *v1.CreateJobRequest) (*v1.CreateJobResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("joex.v1.JobService.CreateJob is not implemented"))
}
