// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: joex/v1/datatype.proto

package joexv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_DATA_TYPE_UNSPECIFIED DataType = 0
	DataType_DATA_TYPE_BOOL        DataType = 1
	DataType_DATA_TYPE_INT         DataType = 2
	DataType_DATA_TYPE_FLOAT       DataType = 3
	DataType_DATA_TYPE_STRING      DataType = 4
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_BOOL",
		2: "DATA_TYPE_INT",
		3: "DATA_TYPE_FLOAT",
		4: "DATA_TYPE_STRING",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_BOOL":        1,
		"DATA_TYPE_INT":         2,
		"DATA_TYPE_FLOAT":       3,
		"DATA_TYPE_STRING":      4,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_joex_v1_datatype_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_joex_v1_datatype_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_joex_v1_datatype_proto_rawDescGZIP(), []int{0}
}

type Arg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DataType               `protobuf:"varint,1,opt,name=type,proto3,enum=joex.v1.DataType" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arg) Reset() {
	*x = Arg{}
	mi := &file_joex_v1_datatype_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg) ProtoMessage() {}

func (x *Arg) ProtoReflect() protoreflect.Message {
	mi := &file_joex_v1_datatype_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg.ProtoReflect.Descriptor instead.
func (*Arg) Descriptor() ([]byte, []int) {
	return file_joex_v1_datatype_proto_rawDescGZIP(), []int{0}
}

func (x *Arg) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *Arg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_joex_v1_datatype_proto protoreflect.FileDescriptor

const file_joex_v1_datatype_proto_rawDesc = "" +
	"\n" +
	"\x16joex/v1/datatype.proto\x12\ajoex.v1\x1a\x1bbuf/validate/validate.proto\"R\n" +
	"\x03Arg\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.joex.v1.DataTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12\x1c\n" +
	"\x05value\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05value*w\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDATA_TYPE_BOOL\x10\x01\x12\x11\n" +
	"\rDATA_TYPE_INT\x10\x02\x12\x13\n" +
	"\x0fDATA_TYPE_FLOAT\x10\x03\x12\x14\n" +
	"\x10DATA_TYPE_STRING\x10\x04B\x89\x01\n" +
	"\vcom.joex.v1B\rDatatypeProtoP\x01Z.github.com/ashep/joex/sdk/proto/joex/v1;joexv1\xa2\x02\x03JXX\xaa\x02\aJoex.V1\xca\x02\aJoex\\V1\xe2\x02\x13Joex\\V1\\GPBMetadata\xea\x02\bJoex::V1b\x06proto3"

var (
	file_joex_v1_datatype_proto_rawDescOnce sync.Once
	file_joex_v1_datatype_proto_rawDescData []byte
)

func file_joex_v1_datatype_proto_rawDescGZIP() []byte {
	file_joex_v1_datatype_proto_rawDescOnce.Do(func() {
		file_joex_v1_datatype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_joex_v1_datatype_proto_rawDesc), len(file_joex_v1_datatype_proto_rawDesc)))
	})
	return file_joex_v1_datatype_proto_rawDescData
}

var file_joex_v1_datatype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_joex_v1_datatype_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_joex_v1_datatype_proto_goTypes = []any{
	(DataType)(0), // 0: joex.v1.DataType
	(*Arg)(nil),   // 1: joex.v1.Arg
}
var file_joex_v1_datatype_proto_depIdxs = []int32{
	0, // 0: joex.v1.Arg.type:type_name -> joex.v1.DataType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_joex_v1_datatype_proto_init() }
func file_joex_v1_datatype_proto_init() {
	if File_joex_v1_datatype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_joex_v1_datatype_proto_rawDesc), len(file_joex_v1_datatype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_joex_v1_datatype_proto_goTypes,
		DependencyIndexes: file_joex_v1_datatype_proto_depIdxs,
		EnumInfos:         file_joex_v1_datatype_proto_enumTypes,
		MessageInfos:      file_joex_v1_datatype_proto_msgTypes,
	}.Build()
	File_joex_v1_datatype_proto = out.File
	file_joex_v1_datatype_proto_goTypes = nil
	file_joex_v1_datatype_proto_depIdxs = nil
}
