// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: joex/v1/pipeline.proto

package joexv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Engine int32

const (
	Engine_ENGINE_UNSPECIFIED Engine = 0
	Engine_ENGINE_JS          Engine = 1
)

// Enum value maps for Engine.
var (
	Engine_name = map[int32]string{
		0: "ENGINE_UNSPECIFIED",
		1: "ENGINE_JS",
	}
	Engine_value = map[string]int32{
		"ENGINE_UNSPECIFIED": 0,
		"ENGINE_JS":          1,
	}
)

func (x Engine) Enum() *Engine {
	p := new(Engine)
	*p = x
	return p
}

func (x Engine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Engine) Descriptor() protoreflect.EnumDescriptor {
	return file_joex_v1_pipeline_proto_enumTypes[0].Descriptor()
}

func (Engine) Type() protoreflect.EnumType {
	return &file_joex_v1_pipeline_proto_enumTypes[0]
}

func (x Engine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Engine.Descriptor instead.
func (Engine) EnumDescriptor() ([]byte, []int) {
	return file_joex_v1_pipeline_proto_rawDescGZIP(), []int{0}
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        Engine                 `protobuf:"varint,1,opt,name=engine,proto3,enum=joex.v1.Engine" json:"engine,omitempty"`
	Opts          map[string]*Arg        `protobuf:"bytes,2,rep,name=opts,proto3" json:"opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AllowFail     bool                   `protobuf:"varint,3,opt,name=allow_fail,json=allowFail,proto3" json:"allow_fail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_joex_v1_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_joex_v1_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_joex_v1_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *Step) GetEngine() Engine {
	if x != nil {
		return x.Engine
	}
	return Engine_ENGINE_UNSPECIFIED
}

func (x *Step) GetOpts() map[string]*Arg {
	if x != nil {
		return x.Opts
	}
	return nil
}

func (x *Step) GetAllowFail() bool {
	if x != nil {
		return x.AllowFail
	}
	return false
}

type CreatePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*Step                `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineRequest) Reset() {
	*x = CreatePipelineRequest{}
	mi := &file_joex_v1_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRequest) ProtoMessage() {}

func (x *CreatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_joex_v1_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRequest.ProtoReflect.Descriptor instead.
func (*CreatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_joex_v1_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePipelineRequest) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type CreatePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineResponse) Reset() {
	*x = CreatePipelineResponse{}
	mi := &file_joex_v1_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineResponse) ProtoMessage() {}

func (x *CreatePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_joex_v1_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineResponse.ProtoReflect.Descriptor instead.
func (*CreatePipelineResponse) Descriptor() ([]byte, []int) {
	return file_joex_v1_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePipelineResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_joex_v1_pipeline_proto protoreflect.FileDescriptor

const file_joex_v1_pipeline_proto_rawDesc = "" +
	"\n" +
	"\x16joex/v1/pipeline.proto\x12\ajoex.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16joex/v1/datatype.proto\"\xca\x01\n" +
	"\x04Step\x12/\n" +
	"\x06engine\x18\x01 \x01(\x0e2\x0f.joex.v1.EngineB\x06\xbaH\x03\xc8\x01\x01R\x06engine\x12+\n" +
	"\x04opts\x18\x02 \x03(\v2\x17.joex.v1.Step.OptsEntryR\x04opts\x12\x1d\n" +
	"\n" +
	"allow_fail\x18\x03 \x01(\bR\tallowFail\x1aE\n" +
	"\tOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.joex.v1.ArgR\x05value:\x028\x01\"F\n" +
	"\x15CreatePipelineRequest\x12-\n" +
	"\x05steps\x18\x01 \x03(\v2\r.joex.v1.StepB\b\xbaH\x05\x92\x01\x02\b\x01R\x05steps\"(\n" +
	"\x16CreatePipelineResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*/\n" +
	"\x06Engine\x12\x16\n" +
	"\x12ENGINE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tENGINE_JS\x10\x012d\n" +
	"\x0fPipelineService\x12Q\n" +
	"\x0eCreatePipeline\x12\x1e.joex.v1.CreatePipelineRequest\x1a\x1f.joex.v1.CreatePipelineResponseB\x89\x01\n" +
	"\vcom.joex.v1B\rPipelineProtoP\x01Z.github.com/ashep/joex/sdk/proto/joex/v1;joexv1\xa2\x02\x03JXX\xaa\x02\aJoex.V1\xca\x02\aJoex\\V1\xe2\x02\x13Joex\\V1\\GPBMetadata\xea\x02\bJoex::V1b\x06proto3"

var (
	file_joex_v1_pipeline_proto_rawDescOnce sync.Once
	file_joex_v1_pipeline_proto_rawDescData []byte
)

func file_joex_v1_pipeline_proto_rawDescGZIP() []byte {
	file_joex_v1_pipeline_proto_rawDescOnce.Do(func() {
		file_joex_v1_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_joex_v1_pipeline_proto_rawDesc), len(file_joex_v1_pipeline_proto_rawDesc)))
	})
	return file_joex_v1_pipeline_proto_rawDescData
}

var file_joex_v1_pipeline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_joex_v1_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_joex_v1_pipeline_proto_goTypes = []any{
	(Engine)(0),                    // 0: joex.v1.Engine
	(*Step)(nil),                   // 1: joex.v1.Step
	(*CreatePipelineRequest)(nil),  // 2: joex.v1.CreatePipelineRequest
	(*CreatePipelineResponse)(nil), // 3: joex.v1.CreatePipelineResponse
	nil,                            // 4: joex.v1.Step.OptsEntry
	(*Arg)(nil),                    // 5: joex.v1.Arg
}
var file_joex_v1_pipeline_proto_depIdxs = []int32{
	0, // 0: joex.v1.Step.engine:type_name -> joex.v1.Engine
	4, // 1: joex.v1.Step.opts:type_name -> joex.v1.Step.OptsEntry
	1, // 2: joex.v1.CreatePipelineRequest.steps:type_name -> joex.v1.Step
	5, // 3: joex.v1.Step.OptsEntry.value:type_name -> joex.v1.Arg
	2, // 4: joex.v1.PipelineService.CreatePipeline:input_type -> joex.v1.CreatePipelineRequest
	3, // 5: joex.v1.PipelineService.CreatePipeline:output_type -> joex.v1.CreatePipelineResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_joex_v1_pipeline_proto_init() }
func file_joex_v1_pipeline_proto_init() {
	if File_joex_v1_pipeline_proto != nil {
		return
	}
	file_joex_v1_datatype_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_joex_v1_pipeline_proto_rawDesc), len(file_joex_v1_pipeline_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_joex_v1_pipeline_proto_goTypes,
		DependencyIndexes: file_joex_v1_pipeline_proto_depIdxs,
		EnumInfos:         file_joex_v1_pipeline_proto_enumTypes,
		MessageInfos:      file_joex_v1_pipeline_proto_msgTypes,
	}.Build()
	File_joex_v1_pipeline_proto = out.File
	file_joex_v1_pipeline_proto_goTypes = nil
	file_joex_v1_pipeline_proto_depIdxs = nil
}
