on:
  - push
  - workflow_dispatch

jobs:
  lint:
    uses: ashep/ci/.github/workflows/go-lint.yaml@v1

  test:
    uses: ashep/ci/.github/workflows/go-test.yaml@v1
    secrets:
      dotenv: |
        LOCALSTACK_AUTH_TOKEN=${{ secrets.LOCALSTACK_AUTH_TOKEN }}

  build:
    needs:
      - lint
      - test
    uses: ashep/ci/.github/workflows/go-build.yaml@v1
